# EN: Base image using latest Nginx version
# ES: Imagen base utilizando la última versión de Nginx
FROM nginx:latest

# EN: Copy custom web page into Nginx default directory
# ES: Copiar página web personalizada al directorio por defecto de Nginx
COPY app/index.html /usr/share/nginx/html/index.html
