# EN: Disable authentication for local lab environment
# ES: Desactivar autenticación para entorno local de laboratorio
auth_enabled: false

server:

  # EN: Loki listening port
  # ES: Puerto de escucha de Loki
  http_listen_port: 3100

common:
  path_prefix: /loki

  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

  replication_factor: 1

  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem

      # EN: Loki schema version
      # ES: Versión de esquema Loki
      schema: v13

      index:
        prefix: index_

        # EN: Generate index every 24h
        # ES: Generar índice cada 24h
        period: 24h
