---
- name: Install and configure Nginx
  hosts: web
  become: true

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Deploy custom index page
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
      notify: Restart Nginx

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true
